name: Lint
on: [push, pull_request]

jobs:
  lint:
    name: Node.js
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: ["14.x"]

    steps:
      - name: Checkout https://github.com/${{ github.repository }}@${{ github.ref }}
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@49933ea5288caeca8642195f2b846f80e6b81655 # v4.4.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run linter
        run: npx --no-install jshint@2.12.0 .
